### ISSUE TITLE
bad_chs parsed as nan for RVG25

### ISSUE THREAD

**Issue by jthermiz** [BouchardLab/nsds_lab_to_nwb#113]
`bad_chs` gets parsed as `nan` for this experiment notes even though the entries look fine. Error may be due to trailing space or incomplete row. Possible solutions are extra processing to remove trailing space in an automated fashion.

https://docs.google.com/spreadsheets/d/1y7th254ynr3o7S-zqT99pLid-dgjWBJGi2Gag7jdW1Q/edit#gid=1688094965

**Comment by jihyunbak** [comment]
Hi @jthermiz , could you try running this block with the `metadata_save_path` kwarg? Normally you get three yaml files from different points of metadata processing (input, input_clean, final), although in this case you may not get all three files if error occurs in MetadataManager. It would be helpful to see what you have in the `bad_chs` field of these yaml files. You can follow one of the two routes below

1) Assuming that you have all environment variables set up, it would be easiest to `cd` to the `scripts/` folder and run the following in the command line (replace `_B00` with the actual block number).

```bash
./block_test.sh RVG25_B00
```

2) Or if you prefer to whatever script you have been using, you can include this keyword argument when constructing `NWBBuilder`. Feel free to use a different temporary directory for the metadata save path.

```python
builder = NWBBuilder(**all_your_usual_kwargs, metadata_save_path='_test/')
```

**Comment by jihyunbak** [comment]
Looking at the log would be helpful too!

**Comment by jthermiz** [comment]
@jihyunbak I'm resolved this initial issue, but then I realized that bad_chs was not written to the nwb file. I added code to do that. It works except when there are no bad channels (ie nan --> empty list). Nwb doesn't seem to like empty list. Do you have a suggestion for how to store bad_chs if there aren't any. Alternatively we could just not write bad_chs is there aren't any, but I could see how it would be inconvenient to a user who expected that field to be there, but in some files doesn't have it.

**Comment by jthermiz** [comment]
Here's the commit on my fork: https://github.com/jthermiz/nsds_lab_to_nwb/tree/bad_chs

**Comment by jthermiz** [comment]
Since I couldn't find an easy to way add bad_chs when there are none, I changed the behavior to omit bad_chs when there are none
