### ISSUE TITLE
incorrect metadata values for stim trial structures

### ISSUE THREAD

**Issue by jihyunbak** [BouchardLab/nsds_lab_to_nwb#129]
Current stimulus metadata are incorrect in many places. Working on a fix.

Here's a teaser:
https://github.com/BouchardLab/pyraat/blob/main/notebooks/auditory_stimuli_check.ipynb

**Comment by jihyunbak** [comment]
fixing this would also resolve these issues:

- #114 
- #127

**Comment by jthermiz** [comment]
Thanks for going through all the stimuli and optimizing the parsing @jihyunbak ! It looks like you've solved all of the mark finding issues.

**Comment by jthermiz** [comment]
I just realized that the signals you are analyzing are the .wav signals but you will eventually want to analyze the marker signal as recorded by the neural acquisition system (in this case TDT) and optimize detection of those markers. The sampling rates are different for these signals (Audio: 96k? vs TDT: ~12k or ~25k) and when the stimulus is played is variable (depends on when human presses play on DVD player) wrt to the start of the neural recording. Does that make sense?

**Comment by jihyunbak** [comment]
@jthermiz You were right - I did the analysis on the recorded marks instead. It required a different solution for the missing wn2 marks (the first mark was much lower than all others), which is now part of PR #130
