### ISSUE TITLE
make references to metadata repo relative rather than absolute

### ISSUE THREAD

**Issue by jihyunbak** [BouchardLab/nsds_lab_to_nwb#16]
make references to files in NSDSLab-NWB-metadata relative rather than absolute

(for now it is assumed that you cloned the metadata repo under your `~/Src/`)

**Comment by JesseLivezey** [comment]
https://docs.python.org/3/distutils/setupscript.html#installing-package-data

**Comment by JesseLivezey** [comment]
https://github.com/wimglenn/resources-example

**Comment by JesseLivezey** [comment]
We could also rely on environment variables for some of these things as an alternative.
