### ISSUE TITLE
detect sample_rate from TDT/HTK

### ISSUE THREAD

**Issue by jihyunbak** [BouchardLab/nsds_lab_to_nwb#19]
Detect `sample_rate` for both TDT/HTK pipelines
- [x] TDT pipeline - does this
- [ ] HTK pipeline - not yet
    - can we also read `sample_rate` from HTK files? — current HTK pipeline does not do this, but see Chang lab code [here](https://github.com/BouchardLab/process_ecog/blob/master/ecog/utils/HTK.py)

Ultimately we want to drop `sample_rate` from metadata (no user input)

**Comment by jthermiz** [comment]
@jihyunbak I think we can close this issue, right?

**Comment by jihyunbak** [comment]
I was thinking we don't have rate detection from HTK. I edited the issue description with a checklist! (New feature I learned)

**Comment by jihyunbak** [comment]
#67 can tick the second checkbox for HTK
