### ISSUE TITLE
TDT pipeline errors due to metadata parsing

### ISSUE THREAD

**Issue by jthermiz** [BouchardLab/nsds_lab_to_nwb#23]
The white noise label in the metadata file ("block_data.csv") is not what NWB expects. The error occurs in:

`class MarkTokenizer` line 19 value error is raised

As reported by Vannesa.

**Comment by jthermiz** [comment]
It looks like the error is due to a mismatch what string the tokenizer is looking for. Changing line 16 from:

`elif 'wn' in stim_name:`  

to

`elif 'White noise' in stim_name:`

solves the problem. However, the main issue is that `StimulusOriginator` is does not seem built out to handle metadata parsing for TDT data.

**Comment by jihyunbak** [comment]
This issue will be addressed primarily by PR #40

**Comment by jihyunbak** [comment]
There may be more downstream errors until we resolve the other issue #14, but I will let this issue close once the stimulus mapping is completed (PR #45)
