### ISSUE TITLE
Fix filename convention & organization for block metadata files

### ISSUE THREAD

**Issue by jihyunbak** [BouchardLab/nsds_lab_to_nwb#3]
Perhaps organize the block metadata files by rats?

For example,

- current (temporary) organization: metadata_path/yaml/R00_B00.yaml
- alternative organization: metadata_path/yaml/R00/R00_B00.yaml

All changes in the metadata repo should be reflected in MetadataManager.

What else?

**Comment by jthermiz** [comment]
I'll like the alternative organization R00/R00_B00.yaml

Do we want to continue to use R00_B00 convention? What happens when we reach 99+ 1? Do we increment to R100 or go back to R00?

**Comment by KrisBouchard** [comment]
Lets go with R####_B### just to be safe.

If we get to R10000, I will simply retire.

Make sense?

--
KB (he/him/his)

Kristofer Bouchard, Ph.D.
Computational Biology Staff Scientist

PI, Neural Systems and Data Science Lab <http://bouchardlab.lbl.gov>,
Biological Systems & Engineering Division, LBNL
Acting Lead, Computational Biosciences Group
<https://crd.lbl.gov/computational-biosciences>,
Computational Research Divisions, LBNL

Assistant Adjunct Professor
Helen Wills Neuroscience Institute &
Redwood Center for Theoretical Neuroscience,
UC Berkeley

Kavli Institute for Fundamental Neuroscience
UC San Francisco

**Comment by jihyunbak** [comment]
Update:

- [x] Organizing into subdirectories by rat names: done.
- [ ] Forcing animal/block name conventions like R##### or B###: not yet.

Note on the animal/block name conventions: essentially, these conventions should be implemented on the metadata side (and when saving the raw data files). The builder simply takes two strings, like ("R00100", "B001"), and it won't care how the strings are formatted inside. So we can use (animal, block) names like ("MyLittleRat", "TestBlock") without any problem, as long as there are matching raw data files. This flexibility will make thing easier for simulated datasets, because you can just treat it like an experiment where the animal name is "Simulation".
