### ISSUE TITLE
add session start time

### ISSUE THREAD

**Issue by jihyunbak** [BouchardLab/nsds_lab_to_nwb#42]
- [x] get session start time info

    perhaps easiest to draw from TDT

    input from @jthermiz: use TDTReader to pull this

    ```
    mytdt = TDTReader(tdt_path)
    mytdt.tdt_obj['info']
    ```

    then extract the `start_date` and `utc_start_time` fields

- [x] use this to fill the `session_start_time` metadata in NWB file:

    https://github.com/BouchardLab/nsds_lab_to_nwb/blob/b7c5c269bcdae8680f10161cd9cab509a5ee8e5b/nsds_lab_to_nwb/nwb_builder.py#L138-L143

    may need modification to add this _after_ we read the data streams.

**Comment by JesseLivezey** [comment]
We'll also have to make sure that the stim/mark/trials get the right relative times as well.

**Comment by jihyunbak** [comment]
According to [this NWB tutorial](https://pynwb.readthedocs.io/en/stable/tutorials/general/file.html#time-series-data), setting `start_time=0` for a TimeSeries object indicates that it starts 0 seconds after the NWB-wise `session_start_time`.

Because all our start times are coming from the same TDT object, I think we can simply set the NWB `session_start_time` and set all relative TimeSeries start times to 0.

**Comment by jihyunbak** [comment]
For example, we are using time offsets for stimulus:

https://github.com/BouchardLab/nsds_lab_to_nwb/blob/863642786ad8815addbfe1d1b0962ab5354abc99/nsds_lab_to_nwb/components/stimulus/wav_manager.py#L27-L41
