### ISSUE TITLE
need electrode locations (anatomical region) for both old and new experiments

### ISSUE THREAD

**Issue by jihyunbak** [BouchardLab/nsds_lab_to_nwb#48]
see note on best practices [here](https://www.nwb.org/best-practices/#times)

**Comment by jthermiz** [comment]
Possible names for anatomical location based on Allen Mouse Map (per NWB guidance).

![image](https://user-images.githubusercontent.com/5800317/121947655-20967e00-cd0b-11eb-9dce-175a40fcaad0.png)

I still what I proposed earlier should be sufficient. Right temporal lobe with distances from anatomical landmarks (posterior and lateral ridge)
