### ISSUE TITLE
confirm filtering details for the electrodes table

### ISSUE THREAD

**Issue by jihyunbak** [BouchardLab/nsds_lab_to_nwb#49]
From Ryan's review on `R56_B13` test output:
> The “filtering” column in the electrodes table contains the text “Low-Pass Filtered to Nyquist frequency”. To be clear, is this based on the sampling rate of 6103.515625 or a different sampling rate?

**Comment by jihyunbak** [comment]
@VBaratham @JesseLivezey Could you please comment on this?

**Comment by VBaratham** [comment]
I don't know what that text meant - could just be junk we put in because NWB needed something there

**Comment by jthermiz** [comment]
I doubt that the signal was low pass filtered at precisely half of the sample rate. Filters are not ideal so there would be some aliasing error due if the cutoff was Fs/2. I asked Vanessa for this cutoff  in another issue.

**Comment by jthermiz** [comment]
Vanessa said in another issue that the signal is low pass filtered at 45% of the sample rate.

The data is also high pass filtered at 2 Hz.
