### ISSUE TITLE
add a description to each ElectricalSeries

### ISSUE THREAD

**Issue by jihyunbak** [BouchardLab/nsds_lab_to_nwb#50]
(edit both TdtManager and HtkManager)

**Comment by jthermiz** [comment]
Feedback from Ryan

"My take on descriptions for TimeSeries objects is that they should provide a summary of the data for a random person browsing the data in a data archive, and it helps to include relevant metadata even though those are described elsewhere. For your ElectricalSeries, I would say something like "Raw / filtered recordings from 1/2/3/4 polytrodes in brain regions A, B, C, sampled at x Hz (include downsampling information if performed)""

**Comment by jthermiz** [comment]
Potentially add description code in `neural_data_originator` as well as resample code

**Comment by jthermiz** [comment]
One thing I just thought about is whether we need to resample the stimulus waveforms as well.

**Comment by jihyunbak** [comment]
Addressed by #78. Closing.
