### ISSUE TITLE
better descriptions for stimulus and mark TimeSeries

### ISSUE THREAD

**Issue by jihyunbak** [BouchardLab/nsds_lab_to_nwb#51]
From Ryan's review: Use a more descriptive description for raw_stimulus and recorded_mark. What do the values represent?

See WavManager and MarkManager, respectively.

**Comment by jihyunbak** [comment]
@VBaratham For each timeseries (stimulus/mark) what would be
- a better name to replace `raw_stimulus` and `recorded_mark` (if any)
- ~1 sentence description text?

Thanks!

**Comment by JesseLivezey** [comment]
Also, what are sensible units for these and the stimulus .wav?

**Comment by VBaratham** [comment]
maybe "stimulus_waveform" and "stim_onset_marks"? I'm not sure I can come up with names that fully describe them without being too long

I dont know what units either of them are in. The mark track doesn't really have units, it's just a series of pulses

**Comment by jthermiz** [comment]
I believe `raw_stimulus` and `recorded_mark` are the same thing as `aud1` and `mrk1` in which case it should be in units of volts. @vngutierrez can you confirm what the units of `mrk1` and `aud1` are in volts?

Also can @vngutierrez can you please tell us the low pass cutoff filter (anti-aliasing) used in the rpvds program? My guess is it's close to 40% of the sample rate.

**Comment by vngutierrez** [comment]
> @vngutierrez can you confirm what the units of `mrk1` and `aud1` are in volts?

- @jthermiz Yes they are in volts!

> Also can @vngutierrez can you please tell us the low pass cutoff filter (anti-aliasing) used in the rpvds program? My guess is it's close to 40% of the sample rate.

- @jthermiz I can confirm this tomorrow morning

**Comment by vngutierrez** [comment]
> Also can @vngutierrez can you please tell us the low pass cutoff filter (anti-aliasing) used in the rpvds program? My guess is it's close to 40% of the sample rate.

- @jthermiz the antialiasing filter is at 45% the overall sampling rate
