### ISSUE TITLE
FileNotFoundError while importing list of stimuli yaml file

### ISSUE THREAD

**Issue by jihyunbak** [BouchardLab/nsds_lab_to_nwb#52]
> I run into this error when I try to run this:
> 
> FileNotFoundError: [Errno 2] No such file or directory: '../../_data/list_of_stimuli.yaml'
> 
> I think you implemented the importlib.resource thing which is how you get it to work?

_Originally posted by @jthermiz in https://github.com/BouchardLab/nsds_lab_to_nwb/pull/45#discussion_r650332212_

**Comment by jihyunbak** [comment]
@jthermiz could you run the test again `python -u test_wav_manager.py` from the updated main branch?

**Comment by jthermiz** [comment]
@jihyunbak I don't get this error anymore, so I think this is resolved. I do get another error related to stimulus path.
