### ISSUE TITLE
add unit to subject weights in metadata

### ISSUE THREAD

**Issue by jihyunbak** [BouchardLab/nsds_lab_to_nwb#53]
> Is the weight unit pre-defined in nwb? The units of weight are in grams

_Originally posted by @jthermiz in https://github.com/BouchardLab/nsds_lab_to_nwb/issues/46#issuecomment-859986965_

**Comment by jthermiz** [comment]
I found this in the documentation that is relevant:

![image](https://user-images.githubusercontent.com/5800317/121945126-49694400-cd08-11eb-8fc9-e5873d1933e9.png)

It looks like the weight field does not natively support a unit type. Perhaps we appended 'g' to the weight to indicate it's in grams?

**Comment by jthermiz** [comment]
https://nwb-schema.readthedocs.io/en/latest/format.html?highlight=subject%20weight#subject
