### ISSUE TITLE
unrecognized pytest option -n

### ISSUE THREAD

**Issue by jihyunbak** [BouchardLab/nsds_lab_to_nwb#75]
this is after doing `conda env update -f environment.yml`

```bash
(nsdsnwb) [jhbak@catscan nsds_lab_to_nwb]$ pytest --basetemp=tmp -sv -n 8 tests
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: -n
  inifile: None
  rootdir: /pool0/clusterfs/bebb/users/jhbak/proj/nsds_lab_to_nwb
```

@JesseLivezey  is the `-n 8` part intended?

**Comment by jihyunbak** [comment]
but I was able to run the test after removing `-n 8`

**Comment by JesseLivezey** [comment]
That line should work if `pytest-xdist` is installed
https://github.com/BouchardLab/nsds_lab_to_nwb/blob/dc5ab965e6d9f6623341cf95077c4089cbfa7ae7/environment.yml#L33

Can you check if it made it into your environment? It runs multiple tests in parallel, which will be nice for the tests that try and run the whole pipeline on multiple blocks. Removing it will just run them serially, which is also fine (just slower).

**Comment by jihyunbak** [comment]
Aha, my bad - I was in my old, differently named environment `nsdsnwb` when the `conda env update` created a new, standard-named environment `nsds_nwb`. It works in the new env. Thanks @JesseLivezey !
