### ISSUE TITLE
need file paths for tone_diagnostic stimulus

### ISSUE THREAD

**Issue by jihyunbak** [BouchardLab/nsds_lab_to_nwb#87]
https://github.com/BouchardLab/nsds_lab_to_nwb/blob/e2663acbc310416134281c2e5cdbf5493f7d312b/nsds_lab_to_nwb/metadata/resources/list_of_stimuli.yaml#L50-L55

@jthermiz @vngutierrez

**Comment by vngutierrez** [comment]
@jihyunbak I couldn't find a `tone_diagnostic.wav` file of any kind, but I did find a `Tone_diag_stim.stimVls.mat` and copied it onto catsan.

I can make a .wav for this stimulus though.

**Comment by jihyunbak** [comment]
Thanks @vngutierrez !

If there are no available wav files for audio and marker data for this stimulus (and I understand you have the original DVDs that you use in experiments?), I think we should create wav files and add to the stimulus library. Could you talk to @jthermiz and @KrisBouchard about this next week? Thanks again!

**Comment by vngutierrez** [comment]
@jihyunbak I created the new .was files but the sampling rate is low and the audio sounds of bad quality. When I go back next week, I can make better files and dump them onto catscan.
