### ISSUE TITLE
No tdt_path found for baseline stimulus

### ISSUE THREAD

**Issue by jthermiz** [BouchardLab/nsds_lab_to_nwb#96]
I get the following error when trying to convert `RVG21_B12`, which is a baseline recording. Note this is after adding a `baseline.yaml` to the `NSDSLab-MetaData` repo

**Comment by jihyunbak** [comment]
Hi @jthermiz, could you add the block data to `/clusterfs/NSDS_data/raw/RVG21/RVG21_B12/` so I could test? Currently I don't have any baseline test block.

**Comment by jthermiz** [comment]
@vngutierrez Could you please upload this too?

**Comment by vngutierrez** [comment]
@jihyunbak @jthermiz Sure I'll upload that block today

**Comment by jthermiz** [comment]
There are several issues remaining with converting a baseline recording.

- The program tries to look for a stimuli file and add that to nwb content.
