### ISSUE TITLE
Need a good test block with TIMIT stimulus

### ISSUE THREAD

**Issue by jihyunbak** [BouchardLab/nsds_lab_to_nwb#99]
RVG16_B08 looks like a bad block.

(Specifically, need the test block data in `/clusterfs/NSDS_data/raw/`, along with the metadata yaml)

**Comment by jihyunbak** [comment]
@jthermiz could you please take a look if RVG21 has a TIMIT block? Thanks!

**Comment by jthermiz** [comment]
@jihyunbak Yes according to the notes RVG21_B13 is a good block. I can upload it to catscan tomorrow when I'm in lab

**Comment by jihyunbak** [comment]
@jthermiz Thanks, that would be really useful!

**Comment by jthermiz** [comment]
Sorry for the delay. @vngutierrez If you are in Monday, can you please do this? Otherwise, I'll do it.

**Comment by vngutierrez** [comment]
@jihyunbak I can upload this block today!

**Comment by jihyunbak** [comment]
Thanks a lot @vngutierrez !!

Just a reminder for this block and the baseline block, please also change the permission so that the rest of us can read/write! Normally the read permission is enough, but at this stage either John or I would also need the write permission to generate the metadata yaml file.

**Comment by vngutierrez** [comment]
@jihyunbak Okay! Thank you for letting me know!
